{
 "title": "REST API Monitoring",
 "time": { "from": "2023-11-17T10:15:03.412Z", "to": "2023-11-17T11:46:02.017Z" },
 "templating": {
  "list": [
   { "name": "slo", "label": "Availability SLO (%)", "query": "99" },
   { "name": "latency_slo", "label": "Latency SLO (ms)", "query": "10, 25, 50, 100, 250, 500\n" },
   { "name": "latency_slo_percent", "label": "Latency SLO (%)", "query": "99" },
   {
    "name": "latency_slo_sec",
    "query": {
     "query": "query_result(${latency_slo} / 1000)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "## SLO Windows\n\nAll SLO below are displayed with the following time windows:\n- Instant (based on the scrape interval of Prometheus)\n- 1 hour\n- 1 day"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": {
    "content": "## Availability SLO\n\n${slo}% of requests should succeed, i.e. receive a response with a status different from 5xx"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "## Latency SLO\n\n${latency_slo_percent}% of successful requests (i.e that received a response with a 2xx status) should receive a response in ${latency_slo} ms or less"
   }
  },
  { "title": "Request Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[$__rate_interval]\n    )\n) by (method, uri) > 0",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status!=\"UNKNOWN\"\n        }[$__range]\n    )\n) by (le, method, uri, status)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Availability SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "[Instant] Success rate vs Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"5..\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status!~\"5..\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[1h] Success rate vs Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"5..\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status!~\"5..\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[1d] Success rate vs Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"5..\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status!~\"5..\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[Instant] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_count{\n                uri=~\"/operators.*\",\n                status!~\"5..\"\n            }[$__rate_interval]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[$__rate_interval]\n    )\n)",
     "legendFormat": "Availability"
    },
    { "expr": "${slo} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[1h] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_count{\n                uri=~\"/operators.*\",\n                status!~\"5..\"\n            }[1h]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Availability"
    },
    { "expr": "${slo} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[1d] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_count{\n                uri=~\"/operators.*\",\n                status!~\"5..\"\n            }[1d]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Availability"
    },
    { "expr": "${slo} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[Instant] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_count{\n                        uri=~\"/operators.*\",\n                        status!~\"5..\"\n                    }[$__rate_interval]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\"\n                }[$__rate_interval]\n            )\n        ) or vector(0)\n    ) * 100 - ${slo}\n)\n/\n(100 - ${slo})",
     "legendFormat": "Error Budget"
    }
   ]
  },
  {
   "title": "[1h] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_count{\n                        uri=~\"/operators.*\",\n                        status!~\"5..\"\n                    }[1h]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\"\n                }[1h]\n            )\n        ) or vector(0)\n    ) * 100 - ${slo}\n)\n/\n(100 - ${slo})",
     "legendFormat": "Error Budget"
    }
   ]
  },
  {
   "title": "[1d] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_count{\n                        uri=~\"/operators.*\",\n                        status!~\"5..\"\n                    }[1d]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\"\n                }[1d]\n            )\n        ) or vector(0)\n    ) * 100 - ${slo}\n)\n/\n(100 - ${slo})",
     "legendFormat": "Error Budget"
    }
   ]
  },
  {
   "title": "P${latency_slo_percent} Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }
  },
  {
   "title": "P${latency_slo_percent} Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n    ${latency_slo_percent}/100,\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status=~\"2..\"\n            }[$__rate_interval]\n        )\n    ) by (le, method, uri)\n) > 0",
     "legendFormat": "{{method}} {{uri}}"
    },
    {
     "expr": "histogram_quantile(\n    ${latency_slo_percent}/100,\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status=~\"2..\"\n            }[$__rate_interval]\n        )\n    ) by (le)\n) > 0",
     "legendFormat": "Combined"
    },
    { "expr": "${latency_slo_sec}", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "P${latency_slo_percent} Latency",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "histogram_quantile(\n    ${latency_slo_percent}/100,\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status!=\"UNKNOWN\"\n            }[$__range]\n        )\n    ) by (le, method, uri, status)\n) >= 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency SLO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "[Instant] Slow rate vs Fast rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "(sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[$__rate_interval]\n    )\n) or vector(0))\n-\nsum(\n    rate(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Slow"
    },
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Fast"
    },
    {
     "expr": "sum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[1h] Slow rate vs Fast rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1h]\n    )\n) or vector(0))\n-\nsum(\n    increase(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Slow"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Fast"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[1d] Slow rate vs Fast rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1d]\n    )\n) or vector(0))\n-\nsum(\n    increase(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Slow"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_bucket{\n            uri=~\"/operators.*\",\n            status=~\"2..\",\n            le=\"${latency_slo_sec}\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Fast"
    },
    {
     "expr": "sum(\n    increase(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "[Instant] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status=~\"2..\",\n                le=\"${latency_slo_sec}\"\n            }[$__rate_interval]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[$__rate_interval]\n    )\n) or vector(0)",
     "legendFormat": "Availability"
    },
    { "expr": "${latency_slo_percent} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[1h] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status=~\"2..\",\n                le=\"${latency_slo_sec}\"\n            }[1h]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1h]\n    )\n) or vector(0)",
     "legendFormat": "Availability"
    },
    { "expr": "${latency_slo_percent} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[1d] Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(\n        rate(\n            http_server_requests_seconds_bucket{\n                uri=~\"/operators.*\",\n                status=~\"2..\",\n                le=\"${latency_slo_sec}\"\n            }[1d]\n        )\n    ) or vector(0)\n)\n/\nsum(\n    rate(\n        http_server_requests_seconds_count{\n            uri=~\"/operators.*\",\n            status=~\"2..\"\n        }[1d]\n    )\n) or vector(0)",
     "legendFormat": "Availability"
    },
    { "expr": "${latency_slo_percent} / 100", "legendFormat": "SLO" }
   ]
  },
  {
   "title": "[Instant] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_bucket{\n                        uri=~\"/operators.*\",\n                        status=~\"2..\",\n                        le=\"${latency_slo_sec}\"\n                    }[$__rate_interval]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\",\n                    status=~\"2..\",\n                }[$__rate_interval]\n            )\n        ) or vector(0)\n    ) * 100 - ${latency_slo_percent}\n)\n/\n(100 - ${latency_slo_percent})",
     "legendFormat": "Error Budget"
    }
   ]
  },
  {
   "title": "[1h] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_bucket{\n                        uri=~\"/operators.*\",\n                        status=~\"2..\",\n                        le=\"${latency_slo_sec}\"\n                    }[1h]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\",\n                    status=~\"2..\",\n                }[1h]\n            )\n        ) or vector(0)\n    ) * 100 - ${latency_slo_percent}\n)\n/\n(100 - ${latency_slo_percent})",
     "legendFormat": "Error Budget"
    }
   ]
  },
  {
   "title": "[1d] Error Budget",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    (\n        (\n            sum(\n                rate(\n                    http_server_requests_seconds_bucket{\n                        uri=~\"/operators.*\",\n                        status=~\"2..\",\n                        le=\"${latency_slo_sec}\"\n                    }[1d]\n                )\n            ) or vector(0)\n        )\n        /\n        sum(\n            rate(\n                http_server_requests_seconds_count{\n                    uri=~\"/operators.*\",\n                    status=~\"2..\",\n                }[1d]\n            )\n        ) or vector(0)\n    ) * 100 - ${latency_slo_percent}\n)\n/\n(100 - ${latency_slo_percent})",
     "legendFormat": "Error Budget"
    }
   ]
  }
 ]
}